id: test-animal-eanaku
title: test-animal-eanaku
version: 2
tags:
  - tag1
  - tag2
description: |
  This is a random job

enabled: true
batchSize: 1000
requireDataset: true
resumeOnRestart: true

triggers:
  - trigger: schedule
    type: incremental
    schedule: @every 120s
  - trigger: schedule
    type: full
    schedule: 0 22 * * 0 # 22:00 every sunday
  - trigger: event
    type: incremental # only works for incremental, incremental is default
    datasets:
      - cima.Farm

tasks:
  - id: task1
    name: process task 1
    description: This is a test
    incremental: true # this is the default, if not set, will always run incremental if main trigger is incremental
    full: false # this is default, this task will run incremental even if full sync
    source:
      latestOnly: false
      dataset: sdb.Owner
      type: DatasetSource
    sink:
      dataset: test.CattleGroup
      type: DatasetSink
  - id: task2
    name: process task 2
    description: This is another test
    full: true # will still run incremental, this will override the incremental when a full sync is triggered
    source:
      batchSize: 10000
      dataset: test.CattleGroup
      type: DatasetSource
    sink:
      tokenProvider: JwtTokenProvider
      type: HttpDatasetSink
      url: "http://datalayer-s3/datasets/skifte.TaskGpsPointCompleted/entities"
    dependsOn:
      - task1
onSuccess:
  - SuccessReport
onFailure:
  - ErrorReport

